### ISSUE TITLE
Map grunnkrets to bydel with `Uoppgitt`

### ISSUE THREAD

**Issue by ybkamaleri** [helseprofil/orgdata#25]
Å aggregere fra grunnkrets til bydel for bydel med status uoppgitt blir vanskelig siden korrespondanse fra grunnkrets er ikke direkte dvs. bydel er ikke de første 6 tall av grunnkrets 8 tall. For 2021 f.eks har disse 4 koder status som `Uoppgitt`:

> code     name         validTo
>030199 Uoppgitt    2021
>110399 Uoppgitt    2021
>460199 Uoppgitt    2021
>500199 Uoppgitt    2021
 
Hvis man antar at bydel uoppgitt `500199` er de med grunnkrets kode `50019999` dvs. de første 6 tall så er det 236 linje, men når man sjekke bydel `500104` for Heimdal f.eks så  er grunnkrets koder fra `50010101` til `50018123`. 

Eller for uoppgitt bydel `110399` er kanskje fra grunnkrets `11039999`? For bydel `110309` for Rennesøy f.eks så er grunnkretser fra `11031101` til `11031406`
 
Hvordan skal vi håndtere disse? Er det riktig å anta at alle `uoppgitt` bydel er 6 tall fra grunnkretskode?  Dvs. `uoppgitt` grunnkretskode `11039999` blir til `uoppgitt` bydel `110399`.

Eller er det bare å inkludere de som har bydel kode i korrespondanse for aggregering?

Uoppgitt bydel får man ikke fra korrespondanse tabell fra SSB som publisert [her](https://www.ssb.no/klass/klassifikasjoner/103/korrespondanser) eller ved å hente via `norgeo` 

`get_correspond("bydel", "grunnkrets")`

**Comment by jorgenRM** [comment]
Dette må vi diskutere med Steinar. Kan du kalle inn til et møte i neste uke? (Jeg reiser på fjellet nå i formiddag.)
Tema:
# Mapping fra f.eks. 11039999 til 110399
        - Legge inn manuelt i norgeo?
        - Er dette R-løypa kan ta seg av?
        - Andre løsninger?
 # Mapping av ugyldig grunnkretskode, la oss si 11039991

**Comment by raniets** [comment]
Logisk: I grunnkretskodete data er det bare de som har ukjent eller ugyldig
grunnkrets som vil få "ukjent bydel" .

I nåværende R-løype, tabell GKBydel2004T, ligger disse omkodingene inne:
grunnkrets i storbyene xxxx9999 -> bydel xxxx99.
(Inkludert de storbykodene som har gamle fylkeskoder.)

For alle andre grunnkretskoder enn "xxxx9999" er det slik at de første seks
sifferne IKKE nødvendigvis er lik bydelskoden! Grunnkretsnummerne (siste
fire siffer) er uavhengige av bydelsnummeret. Eller, for å si det på en
annen måte: Grunnkrets-Delområde-Kommune-Fylke er et sammenhengende
kodeverk, mens Bydeler er en ny kodeliste ved siden av.

Jeg tenker at hvis GK xxxx9999 ikke kan lastes fra SSB-API, så må disse
omkodingene legges inn som faste koder. Enten hardkode i scriptet, eller
(antakelig bedre!) legges i en tabell med faste omkodinger som hentes inn i
tillegg til API-dataene.
Det kan hende det er lurt å ha dette som en egen tabell, og ikke sammen med
resten av Kodeboka. Ellers vil package norgeo bli avhengig av vår kodebok,
så den ikke uten videre kan brukes av andre enn oss.

R-løypa kan vel ikke håndtere dette lenger: Grunnkretsdata vil jo ikke ha
GK-koder når de leses inn i LagFilgruppe, så tabell GKBydel2004T vil aldri
slå inn. Den tabellen er utdatert fra det tidspunktet vi går over til å
kjøre Rådataløypa.

-Steinar

tor. 30. sep. 2021 kl. 10:16 skrev jorgenRM ***@***.***>:

**Comment by ybkamaleri** [comment]
Det var akkurat sånt jeg trodde også at grunnkrets `xxxx9999` er kilde til bydel `xxxx99`. Når det gjelder fylke og kommune så er den håndtert i `norgeo` allerede via `cast_geo` som du kan se [i denne koden](https://github.com/helseprofil/norgeo/blob/master/R/cast-geo.R#L135). Det er lettere siden koden er direkte tilkobling fra tallene.

Jeg fant bare de 4 bydel kodene som har `uoppgitt` i 2021. Bør det kanskje lages `uoppgitt` bydel fra alle grunnkrets storby `xxxx9999` som du nevnte @raniets? Evt. har du oversikt over dem?

**Comment by ybkamaleri** [comment]
Fix in #39
