### ISSUE TITLE
Helper function to compare distinct levels in column across files in file group

### ISSUE THREAD

**Issue by vegardlysne** [helseprofil/orgdata#308]
To check whether all files can be read in using the same specifications, or if something need to be added to the code book. 

Example: Total number of sex sometime reported as 0, sometime as NA, sometime as tot. Results in problems when calling make_file(). 

Solution: Add function find_levels() to map across all files and extract distinct values from selected column.

**Comment by ybkamaleri** [comment]
God forslag! Men lurer på om disse variantene for total ligger i samme fil? Omkoding med `TYP = KB` gjøres per fil. Sender gjerne PR.
