### ISSUE TITLE
make_file "year" -> "GEOyear"

### ISSUE THREAD

**Issue by hanhel** [helseprofil/orgdata#317]
Request to change make_file() option year to GEOyear, to clearify that "year" points to what GEO to use, and not the "production-year" .

**Comment by ybkamaleri** [comment]
Good suggestion, but it might also mean some crashes if @raniets or @vegardlysne are using the function in their code with argument location. For name argument can be solved to rename the argument as `year.geo`. Some changes must also be done in orgdata `options` and some other places that I have to check. Will see..

**Comment by ybkamaleri** [comment]
The arguement `year` is now renamed to `year.geo` to ensure it's working if any functions is still using only `year` as well instead of deprecating the argument.
